### ISSUE TITLE
Problem when picking up bedroll outside of allowed area

### ISSUE THREAD

**Issue by eadsjr** [alextd/RimWorld-UseBedrolls#10]
When the pawn is attempting to pickup the bedroll while it is outside of the area they are allowed to be in, it doesn't work right and spams the dev log. This zone may have changed WHILE they were picking it up, or going to pick it up.

This happened to me on an encounter map while trying to hide in a shelter due to predators on the map... they were stuck trying to pickup the bedroll and failing instead of running to safety.

It would be better if A) it just worked, or B) they didn't try if it is an unallowed area.

**Comment by alextd** [comment]
Solved in latest commit. Super easy actually `{ ignoreForbidden = true };`
